# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shree Chakra Residency
#email: 
description: > # this means to ignore newlines until "baseurl:"
  42


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shreechakra.in" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.


# Build settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

#markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
#analytics: UA-83979019-1

# Comments
#disqus: yes
#disqus-shortname: shreechakra-residency

#social
#twitter: http://twitter.com/@ashwin67
#github: http://github.com/ashwin67

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-include-cache]

theme: "mmistakes/minimal-mistakes@4.23.0"
